### ISSUE TITLE
Server crash on 1.8.9 server

### ISSUE THREAD

**Issue by kwpugh** [primetoxinz/FluxedSolars#1]
Please see crash report.

Another fellow who runs a server PM'd me that it did the same to his server.

http://pastebin.com/raw/XdVUbLiC

**Comment by primetoxinz** [comment]
here is download with a fix since it will take a while for curse to accept
https://www.dropbox.com/s/cmd2f6kxgjb4a1q/fluxedsolars-1.2.jar?dl=0

**Comment by primetoxinz** [comment]
y

**Comment by kwpugh** [comment]
I'll try it now.

**Comment by kwpugh** [comment]
It works, thank you very much and keep up the great mod.   Two server owners are relieved to be able to keep using the mod.

**Comment by kwpugh** [comment]
Btw, not sure if you know, but you can stack the panels one on top of each other and they all gather energy even though only the top panel is exposed.

**Comment by primetoxinz** [comment]
are you able to put nonsolarpanels on top?

**Comment by kwpugh** [comment]
yes, I can put a stone block on top of a panel and it still charges.

**Comment by primetoxinz** [comment]
ok, just fixed it

**Comment by kwpugh** [comment]
will that be in v1.3 then?

**Comment by primetoxinz** [comment]
yep
