### ISSUE TITLE
Messages filling up the server console when Solar panel in use

### ISSUE THREAD

**Issue by kwpugh** [primetoxinz/FluxedSolars#4]
Attached is a screenshot of the messages that constantly hit the console while the solar panel is connected to a buildcraft quarry in 1.8.9.

![spamming](https://cloud.githubusercontent.com/assets/8809210/12494461/dfaee0a8-c04f-11e5-811d-9a486b3728c8.jpg)

The constant messages essentially makes the console useless.

**Comment by primetoxinz** [comment]
Up on curse, V 1.5

**Comment by kwpugh** [comment]
Many thanks.
