### ISSUE TITLE
Texture Problems

### ISSUE THREAD

**Issue by blockbreaker1361** [primetoxinz/FluxedSolars#5]
There are broken textures for the gold solar panel. I am not using any resource packs.

![2016-01-24_10 36 37](https://cloud.githubusercontent.com/assets/5491411/12537192/0d9963c4-c287-11e5-84ec-a347f7cc2331.png)

**Comment by primetoxinz** [comment]
What version are you on?

**Comment by BBoldt** [comment]
Confirmed.

![](http://i.imgur.com/UWrKxpX.jpg)

Version 1.5

**Comment by primetoxinz** [comment]
*shrugs* I rebuilt and it's gone. no idea what happened
